# Generated by Django 4.2.13 on 2024-10-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, default='Tell us about yourself.', null=True)),
                ('phone_number', models.CharField(blank=True, default='+1 123 456 7890', max_length=255, null=True)),
                ('website', models.URLField(blank=True, default='https://example.com', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='files/')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
