# Generated by Django 4.2.13 on 2024-10-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_is_admin_user_is_superuser_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, default='default-banner.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-profilepic.png', null=True, upload_to='images/'),
        ),
    ]
